### PR TITLE
use white Privly icon in dark background

### PR DESCRIPTION
**Pull request by SummerWish**
Switch to white Privly icon in dark background.
Only supports Chrome.

light background
dark background

### CODE REVIEW

**Comment by smcgregor** [comment]
This seems overly complex for what it is. Is all this code necessary because you need a method of reliably determining the color of the page under the icon's position?

**Comment by SummerWish** [comment]
Yes. I think it is simpler than calculating from computed style because we may need to handle transparent/half-transparent issues.

**Comment by smcgregor** [comment]
Does this only support Chrome because it uses Chrome's message API, or is there some other dependency?

**Comment by smcgregor** [comment]
I believe you incorporated these changes into #129. Please reopen if I am incorrect.

**Pull request closed without merging**
